-: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 127.0.0.1
  username: root
  password:
  reconnect: true

production:
  <<: *defaults
  database: no_downtime_migrations_development

development:
  <<: *defaults
  database: no_downtime_migrations_development

test:
  <<: *defaults
  database: no_downtime_migrations_test
