source 'https://rubygems.org'

gem 'rails', '3.2.3'

gem 'hairtrigger', :git => 'git://github.com/vivrass/hair_trigger.git', :require => "hair_trigger"
gem 'no_downtime_migrations', :path => ".."

gem 'mysql2'
gem 'json'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :development, :test do
  gem 'capybara'
end
